### ISSUE TITLE
Very difficult API

### ISSUE THREAD

**Issue by ghost** [crysalead-js/lead-ui#2]
Hi. I was trying to play around a little, and I have to admit the API are not so easy to figure out. Maybe because of no documentation?

I did manage after some tries to build a virtual node, but couldn't mount it.

Even after I used around `37 minutes` to discover that you have 2 two different register and unregister functions - one for `Rendring` and one for `Components`. And in fact `Components` are called inside `Rendring`!! Confusing!

Why you have duplicate functions, and what is the point to use `Components` inside a `Rendring`?

How are you going to mount? I figured out that you first have to register the virtual node inside the `Components` register function through `Rendring`. But still, couldn't mount.

Can this, or will this be simplified?

Say I don't want to use templates, but just use your hyperscript to create a node and a component. How do I do that?

Like this?
1. Create a `new Rendring` instance
2. Call `Components` inside `Rendring`
3. Register virtual node with the `Components` inside `Rendring`
4. Go back again and use `Rendring.mount()` to do the mount?

What I didn't figure out is. The tree or virtual node you want to mount, should it only be a function? Or as in `domLayer`, where you can use plain object without wrapped inside a function?

And now, if I want to dirty check this? How can I access `Component` - `not Components` - inside this  `Rendring`? Or is this something new I have to create a instance of, and then do dirty check?

Very complicated this one!

Couldn't all this be simplified to one `Component` node, like you do for `Tag`?

**Comment by jails** [comment]
There's no documentation right now since it's a work in progress and some features are subject to changes.

The `Renderer` is in gross the "hyperscript" function with additionnal features, that's why it's a class in `lead-ui`. 

To manage componentization on the fly, the `Renderer` needs to be aware of available components during rendering. So the `Renderer` is populated with a `Components` instance which is a simple collection of registered (i.e. available) `Component`. 

Moreover the `Renderer` can support modifiers. By modifiers I mean specific control structures like `each` and `if` (similar to `ng-repeat` `ng-if` in angular). And to do so this modifiers needs to be registered at the `Renderer` level.

If you need a working example of mounting, just go [there](https://github.com/crysalead-js/lead-ui/tree/master/examples/mouse) and run gulp to run the build process which create a valid build in `webroot`.

In all examples:
1. `src/app.js` is the JS entry point
2. `src/app.scss` is the CSS entry point

The `modal` example will also show you how dynamically mount a modal dialog.

This component layer is based on html templates because it's not possible to write a decent component system otherwise. Manually writing a working hyperscript function is way to complex.

So the `Renderer` hyperscript works with the `Transpiler` and you won't be able to write the required hyperscript otherwise (way to complex).

For example you can write such component:

``` js
class HelloWorld extends Component {

  render() {
    return new Tag("div", {attrs: {id: "message"}}, [new Text("Hello World!")]);
  }

}
```

But it's kind useless since you will loose all the benefits of a component layer e.g.:
-  having a consise syntax.
-  allowing modifiers (like `ng-model`, etc.)
-  being able to split your application in components in no time by using custom tag in your templates

The componentization layer is interesting because it make it possible to set a dedicated virtual tree for each component. And this point makes partial refresh possible instead of rerendering the whole hypercript function.

When an application is growing up the hyperscript function become way to complex (especially when you introduced an extra widgetization abstraction layer on it). So the only solution I found is to use a transpilation step. That way I can write simple html templates and the complex hyperscript is generated by the transpiler so I don't have to care about.

**Comment by ghost** [comment]
I understand now. And I like your ideas. Still a few questions. Server side rendring. How it will work out? Es2015 template strings can be used to create html markup or not? 

Xhr and routing will be supported? E.g push state? 

Transitions and animation. How you will do that??

**Comment by jails** [comment]
I found that strings with placeholders + transpiler was more flexible than ES2015 template strings so I didn't used that feature for templating.

Server side components can be rendered using `component.render().toHtml()`. But I will probably need to add the `Render.attach()` method to make the server rendering to work out of the box.

Right now I'm working on the model abstraction and the routing will come next.

Transitions will be managed by routing, and I've no plan for animations yet.

**Comment by ghost** [comment]
You are just a genius man!! I think this will be create. I had hard time using react before because I'm not a fan of jsx. And angularjs complex and slow. So recently I used ractive. But the way they do two way binding has its pit falls. And when I hear your ideas and I see the result of what you did with domlayer. This will be great !

**Comment by jails** [comment]
Glad you like the idea !! Even if the codebase is relatively small compared to other approaches, I think it'll be easier to get the whole capabilities of `lead-ui` when the documentation will be done. There's a couple of interesting ideas which make it expressive and extensible and once explained out, I think the codebase will be easier to get.
