### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by ghost** [crysalead-js/lead-ui#3]
Hi. I have now spent some time to study your code base, and I'm surprised about your use of protoypes. Wherever I look, there is a prototype! Even for the simplest things! That is slow.

Performance is nothing you care about? If you do, why you use prototype so much?  And if you don't use prototype, you use ES2015 classes that are even more slower.

Here is one example:
`ES2015` (ES6) vs ES5 factory: https://jsperf.com/es6-class-vs-es5-object-factory

I think prototypes can be reduced. Have you looked at `Kivi`? https://github.com/localvoid/kivi/blob/master/src/kivi.js  AND citoJS? They both don't use a `new Text instance` for each new text string. `Kivi` just got this feature, and the `updateChildren()` function now handle it. Ofc. You should use `createTextNode()` and not `textContent`. Else you need to wrap it inside a span etc like React and let your users kill the whole webpage with CSS if they use 
`span { display:none}`

At least here in a critical point you could get rid of one prototype. And get the performance up.

Regarding `lead-ui`. I see you are using Classes and extend Class, again slow. Any other way around?

`htmlparser2` uses prototype for each thing it does it seems - at least 7 different prototypes. Have you looked at `T7` before? No prototypes there.

I compared with REACT, Kivi, Bobril, Deku, Mithril etc. now, and your codebase is the only one with so much prototypes 

I don't say this to be bad. I belive in this project, else I hadn't been here :) But there is a whole lot of things that can be optimized - both in `domLayer` and `lead-ui`.

And yes, I know you have or can have a memory performance winner with prototypes comparing to closures etc., but simple functions don't need to have a instance per call. See Virtual DOM. They uses prototype too, but the CreateElement are done outside the prototype.

Even REACT discovered this - that they got a bottleneck with prototypes in the critical parts of their code base, and now converted React.createElement etc. to plain native object. And removed prototype.

And as you may see inside `Inferno` - have you looked? I think he think the same way as you do. He uses a concept called fragments, and value types to archive great performance.

**Comment by jails** [comment]
Javascript is a prototype based language and using prototypes is the way to deal with it. It may looks like slower on a single call but JS Engines has been designed with that prototype layer in mind. And in practice it's not that slow. Just compare the `dom-layer` performance against the other implementations which are using plain objects in the [Virtual DOM benchmark](http://vdom-benchmark.github.io/vdom-benchmark/) and you'll see that performances are really close. And I wouldn't reach such performance if prototype was that slow compared to `{}`.

So I'm thinking about architecture first, and performance second. In a prototype based language I'm using prototypes because it's the way to write better code imo.

And I'm using classes because I prefer the OOP reasoning using classes. It's a personnal preference but I don't think this point can really be a bottleneck at a component level. It would probably be an issue if `Tag` was a class (instead of a prototype) since there can be thousands of dom element in a page. But generally at a higher level you will only have 10 or 100 components in a page. So instantiating 10 or 100 classes will just take a couple of extra ms compared to the prototype based version. So no big deal for me.

**Comment by ghost** [comment]
I understand, and I also see that JSBlocks are using similar approach as you with prototypes as well. And are fast :) Have you tried JSBlocks? And is that a similar approach as you want to accomplish?
http://jsblocks.com/

**Comment by jails** [comment]
Nope I didn't tried JSBlocks, But I would like to write more independant modules. All framework around have their own router, view and model layer but most of the time, they are dedicated to their specific framework. I would like to achieve a better sepration of concerns.
