### ISSUE TITLE
simple way of creating component in ES5 ?

### ISSUE THREAD

**Issue by ghost** [crysalead-js/lead-ui#4]
Hi. Is there any simple way to quickly create components and templates with ES5 directly in the browser, without a ES2015 workflow and extensions of class? I think it would be more user friendly if that was possible, and not force everyone to set up a ES2015 workflow everytime they need a small HTML template. I may think that maybe not all even know what a workflow are. 

Example in domLayer you create a new Tag, directly and you got a virtual element.

Any plans for doing it so simple? As an example, you can look around on all the other libraries.

Example:

```
new Renderer();

var app1 = new Component();
app1.vm() = func();
app1.mount = func();

components.register("app1", app1);
renderer.mount();

// DONE!

```

**Comment by jails** [comment]
It's always possible to write all in vanilla JS but the result will be way more complex that using a workfow.

first you can't register an instance, you need to register a class. So `App1` need to be a function then you'll need to set its correct prototype `App1.prototype = Component;` and set its correct constructor `App1.prototype.constructor = App1;` to be able to register if. And to deal with the template you will need to include the transpiler to have something like that in the template function:

``` js
app1.prototype.template = function() {
   return new Function('$', 's', 'c', 'return ' + transpiler.transpile("<div>your HTML template here</div>") + ';');
} 
```

The fact that backticks aren't supported in browser, dealing with html template in your script will be a pain is the ass. Moreover you'll need to include the transpiler script client side which is big and will slow down all the application since it'll need to parse all template in the fly.

So if you care about performances, it's a way better option to delegate all this transpilling process server side. 

Nowadays using a workflow is imo the simplest way. With the growing popularity of ES6, coffeescript, ATScript and all other features like browserify, JSX, etc. which require some transpiling steps, using a workflow will give you further flexibility to deal with the tech you need.

**Comment by ghost** [comment]
Hi. With backstick you mean as in es2015 template strings? All major browsers this days support it right out of the box. Even Edge. At least on windows computers.

As I said earlier your ideas are great, but be forced to use a workflow everytime I'm setting up some HTML are not my thing. And I  know many are agree about that.

@jails Have a look at how Inferno does it. Read this part of the readme https://github.com/trueadm/inferno#overview  Similar approach as yours, but this works stright in the browser.

So for me there are other options such as Inferno, ractive etc.

For now,I'm backing out from this project now and wish you good luck.
